/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OTCMedicine {
  'name' : string,
  'minAge' : bigint,
  'allergyNotes' : Array<string>,
  'warnings' : string,
  'safetyLevel' : SafetyLevel,
  'pregnancySafe' : [] | [boolean],
  'symptoms' : Array<string>,
  'brandName' : string,
  'dosageInstructions' : string,
}
export type SafetyLevel = { 'avoid' : null } |
  { 'safe' : null } |
  { 'caution' : null };
export interface _SERVICE {
  'getAllMedicines' : ActorMethod<[], Array<OTCMedicine>>,
  'getAllSymptoms' : ActorMethod<[], Array<string>>,
  'getRecommendations' : ActorMethod<
    [Array<string>, bigint, string, Array<string>],
    Array<OTCMedicine>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];