/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Severity = IDL.Variant({
  'mild' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Interaction = IDL.Record({
  'interactionType' : IDL.Text,
  'explanation' : IDL.Text,
  'severity' : Severity,
  'drug1' : IDL.Text,
  'drug2' : IDL.Text,
});
export const SafetyLevel = IDL.Variant({
  'avoid' : IDL.Null,
  'safe' : IDL.Null,
  'caution' : IDL.Null,
});
export const OTCMedicine = IDL.Record({
  'consultDoctorIf' : IDL.Text,
  'avoidIf' : IDL.Text,
  'name' : IDL.Text,
  'minAge' : IDL.Nat,
  'allergyNotes' : IDL.Vec(IDL.Text),
  'warnings' : IDL.Text,
  'safetyLevel' : SafetyLevel,
  'pregnancySafe' : IDL.Opt(IDL.Bool),
  'symptoms' : IDL.Vec(IDL.Text),
  'brandName' : IDL.Text,
  'dosageInstructions' : IDL.Text,
});

export const idlService = IDL.Service({
  'checkInteractions' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(Interaction)],
      ['query'],
    ),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(OTCMedicine)], ['query']),
  'getAllSymptoms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRecommendations' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Vec(OTCMedicine)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Severity = IDL.Variant({
    'mild' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Interaction = IDL.Record({
    'interactionType' : IDL.Text,
    'explanation' : IDL.Text,
    'severity' : Severity,
    'drug1' : IDL.Text,
    'drug2' : IDL.Text,
  });
  const SafetyLevel = IDL.Variant({
    'avoid' : IDL.Null,
    'safe' : IDL.Null,
    'caution' : IDL.Null,
  });
  const OTCMedicine = IDL.Record({
    'consultDoctorIf' : IDL.Text,
    'avoidIf' : IDL.Text,
    'name' : IDL.Text,
    'minAge' : IDL.Nat,
    'allergyNotes' : IDL.Vec(IDL.Text),
    'warnings' : IDL.Text,
    'safetyLevel' : SafetyLevel,
    'pregnancySafe' : IDL.Opt(IDL.Bool),
    'symptoms' : IDL.Vec(IDL.Text),
    'brandName' : IDL.Text,
    'dosageInstructions' : IDL.Text,
  });
  
  return IDL.Service({
    'checkInteractions' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Interaction)],
        ['query'],
      ),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(OTCMedicine)], ['query']),
    'getAllSymptoms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRecommendations' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Vec(OTCMedicine)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };