/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OTCMedicine {
    consultDoctorIf: string;
    avoidIf: string;
    name: string;
    minAge: bigint;
    allergyNotes: Array<string>;
    warnings: string;
    safetyLevel: SafetyLevel;
    pregnancySafe?: boolean;
    symptoms: Array<string>;
    brandName: string;
    dosageInstructions: string;
}
export interface Interaction {
    interactionType: string;
    explanation: string;
    severity: Severity;
    drug1: string;
    drug2: string;
}
export enum SafetyLevel {
    avoid = "avoid",
    safe = "safe",
    caution = "caution"
}
export enum Severity {
    mild = "mild",
    severe = "severe",
    moderate = "moderate"
}
export interface backendInterface {
    checkInteractions(drugs: Array<string>): Promise<Array<Interaction>>;
    getAllMedicines(): Promise<Array<OTCMedicine>>;
    getAllSymptoms(): Promise<Array<string>>;
    getRecommendations(symptoms: Array<string>, age: bigint, pregnancyStatus: string, allergies: Array<string>): Promise<Array<OTCMedicine>>;
}
import type { Interaction as _Interaction, OTCMedicine as _OTCMedicine, SafetyLevel as _SafetyLevel, Severity as _Severity } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkInteractions(arg0: Array<string>): Promise<Array<Interaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInteractions(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInteractions(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedicines(): Promise<Array<OTCMedicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSymptoms(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSymptoms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSymptoms();
            return result;
        }
    }
    async getRecommendations(arg0: Array<string>, arg1: bigint, arg2: string, arg3: Array<string>): Promise<Array<OTCMedicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(arg0, arg1, arg2, arg3);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(arg0, arg1, arg2, arg3);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Interaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interaction): Interaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_OTCMedicine_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OTCMedicine): OTCMedicine {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SafetyLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SafetyLevel): SafetyLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interactionType: string;
    explanation: string;
    severity: _Severity;
    drug1: string;
    drug2: string;
}): {
    interactionType: string;
    explanation: string;
    severity: Severity;
    drug1: string;
    drug2: string;
} {
    return {
        interactionType: value.interactionType,
        explanation: value.explanation,
        severity: from_candid_Severity_n4(_uploadFile, _downloadFile, value.severity),
        drug1: value.drug1,
        drug2: value.drug2
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    consultDoctorIf: string;
    avoidIf: string;
    name: string;
    minAge: bigint;
    allergyNotes: Array<string>;
    warnings: string;
    safetyLevel: _SafetyLevel;
    pregnancySafe: [] | [boolean];
    symptoms: Array<string>;
    brandName: string;
    dosageInstructions: string;
}): {
    consultDoctorIf: string;
    avoidIf: string;
    name: string;
    minAge: bigint;
    allergyNotes: Array<string>;
    warnings: string;
    safetyLevel: SafetyLevel;
    pregnancySafe?: boolean;
    symptoms: Array<string>;
    brandName: string;
    dosageInstructions: string;
} {
    return {
        consultDoctorIf: value.consultDoctorIf,
        avoidIf: value.avoidIf,
        name: value.name,
        minAge: value.minAge,
        allergyNotes: value.allergyNotes,
        warnings: value.warnings,
        safetyLevel: from_candid_SafetyLevel_n9(_uploadFile, _downloadFile, value.safetyLevel),
        pregnancySafe: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.pregnancySafe)),
        symptoms: value.symptoms,
        brandName: value.brandName,
        dosageInstructions: value.dosageInstructions
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avoid: null;
} | {
    safe: null;
} | {
    caution: null;
}): SafetyLevel {
    return "avoid" in value ? SafetyLevel.avoid : "safe" in value ? SafetyLevel.safe : "caution" in value ? SafetyLevel.caution : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
}): Severity {
    return "mild" in value ? Severity.mild : "severe" in value ? Severity.severe : "moderate" in value ? Severity.moderate : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interaction>): Array<Interaction> {
    return value.map((x)=>from_candid_Interaction_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OTCMedicine>): Array<OTCMedicine> {
    return value.map((x)=>from_candid_OTCMedicine_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
